### ISSUE TITLE
Multiple dialog support

### ISSUE THREAD

**Issue by JeneZarr** [aienabled/NoesisGUI.MonoGameWrapper#11]
Hi, I am researching the noesisgui framework for monogame and i am really happy with the wpf support as shown in the sample.
But in a real game i need support to be able to use multiple dialogs / huds instead of one instance of MainWindow.xaml
I tried to show dialogs as usercontrol, but that fails at runtime (designtime in separate project it looks ok tho)

Can you get me on track how to implement multiple dialog support in monogame?

![NoesisGui-dialog](https://user-images.githubusercontent.com/55636081/158034252-b95f010f-9c8c-4257-a4ce-852de86a5203.png)

**Comment by jesusdesantos** [comment]
By the way, we have an implementation of a MessageBox at https://github.com/Noesis/Managed/tree/master/Src/NoesisApp/Core/Src/Core

**Comment by JeneZarr** [comment]
Thanks jesusdesantos for the suggestion, but my question is about monogame with multiple dialogs

**Comment by JeneZarr** [comment]
Resolved by changing Views in MainWindow using DataTemplates

see sample
![NoesisGUI ViewChanger](https://user-images.githubusercontent.com/55636081/165628024-744da1a4-97fa-4011-954c-f2cc3eeb33d2.gif)
[NoesisGUI.ViewChanger.zip](https://github.com/AtomicTorchStudio/NoesisGUI.MonoGameWrapper/files/8577641/NoesisGUI.ViewChanger.zip)
