### ISSUE TITLE
Update for latest Noesis

### ISSUE THREAD

**Issue by Thraka** [aienabled/NoesisGUI.MonoGameWrapper#3]
Hi! I just discovered this and there was a promise on the forums about this being updated last friday. Is there any update?

Thanks!

**Comment by aienabled** [comment]
Hi! Yes, we just released open alpha of our game (using NoesisGUI) and I'm updating this repository to support the latest version of NoesisGUI. It will be done very soon.

**Comment by aienabled** [comment]
Done!

**Comment by aienabled** [comment]
By the way, we're making a large indie game with a custom game engine (integrated with MonoGame for client side) with integration with NoesisGUI. It ships with the completely open source code for UI (and all the gameplay-related code and assets) and supports hot-reloading of everything, including UI code (XAML and C#).
The game is in open alpha now and you can play it free - http://cryofall.com/ (currently it's Windows only; download after registering on http://atomictorch.com with our Game Launcher application).
It's a good chance to see how the UI code can be organized for a large project and how various UI features could be implemented with XAML/NoesisGUI (if you want to open it with VS2017 as we do, please let us know here http://forums.atomictorch.com/ and we will send you the required VS2017 plugin we've made). The code is offered under our custom license so you should not copy-paste it to your projects, but you're free to play around with it as much as you want. Soon it will be possible to create mods for the game.

**Comment by Thraka** [comment]
awesome!! thanks!!

**Comment by Thraka** [comment]
Thank you so much for the wrapper. I cloned the repo and put the SDK in the appropriate folder and everything JUST WORKS. This is amazing. Again, thanks! BTW I bought Void Expanse a long time ago. Thanks for that cool game!

**Comment by aienabled** [comment]
@Thraka, I'm glad it works fine! By the way, I just pushed a small commit to denote where the game logic update code should be added. https://github.com/aienabled/NoesisGUI.MonoGameWrapper/commit/128d9e4ec2519c0c16e2e25e238a20ce40af9010#diff-5b6a1439810b4d344f3c4ebc2e0ce816 It's important to update NoesisGUI input before updating your game logic, and only then update NoesisGUI. This way you can create new NoesisGUI controls or change their properties in your game logic and NoesisGUI will layout them properly right after that. Handling NoesisGUI input before everything else also ensures that your input will be processed in time without any delays, and you can also take processed input from NoesisGUIWrapper right after that to suppress it in your game logic (so if you clicked and NoesisGUI received the click as there was an UI element, you can suppress this click in your game logic to avoid "click-through" problem; same applies for text input).

I'm surprised to learn you're our loyal customer! 👍 VoidExpanse is a nice game, but CryoFall is going to be groundbreaking!

**Comment by Thraka** [comment]
Thanks! Understanding how this all works is slightly difficult but not impossible. Looking at the CryoFall client code helps a lot. For instance, I learned that I needed to treat popup windows as just controls shown on the screen. So I needed to create a blank root element to host all other UI parts such as the normal UI and a popup window.

Regarding input, would I just check the wrapper.Input.Consumed* collections for any count, and if found, ignore input in my game? I'm assuming that is how I'm supposed to detect it.

**Comment by aienabled** [comment]
That's right. We're using a custom input manager which wraps input from MonoGame (`Keyboard.GetState();` and `Mouse.GetState()`) and looks into `wrapper.Input.Consumed*` to suppress input which was consumed by NoesisGUI. I'm really not sure if we can make this a part of this repository as almost every game has its own input processor and our input manager is tightly integrated with other parts of the engine.

**Comment by Thraka** [comment]
I think it is correct to leave it out. My [game engine](https://github.com/thraka/sadconsole) also has an input manager and I'll just do the same thing. 1) Process NoesisGUI 2) check `Consumed*` 3) skip my engine input if needed.

**Comment by Thraka** [comment]
Your MVVM stuff would be awesome to split out into a reusable library for Noesis 😀

**Comment by aienabled** [comment]
> MVVM stuff

Do you mean the auto notification on property change? We're using Roslyn compiler and preprocessing all C# files from the open source part of the game (Core/Mods) to insert property change notification and do some other stuff (like WPF->NoesisGUI namespaces remapping; also `[SyncToClient(...)]` marked properties are expanded to allow engine handle the property change for network replicated states; validation of forbidden to use namespaces in scripting (sandboxing)).

So, this is impossible to split into a reusable library... but a similar feature could be added to any WPF/UWP project with https://github.com/Fody/PropertyChanged and I'm quite sure it will be easy to fork it to include support for NoesisGUI projects.

**Comment by Thraka** [comment]
Do you have any tips for properly loading controls into monogame? I keep getting this error (screenshot is below) randomly though. Since you have worked with the managed wrapper + monogame, I thought I would ask you first before going to the forums.

I'm using the init code from the wrapper library. The first thing loaded is root.xaml

```xaml
<Grid x:Class="Editor.Xaml.Root"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:Editor.Xaml"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
</Grid>
```

The init code (your `CreateNoesisGUI` method) sets up the main viewmodel 

```csharp
private void CreateNoesisGUI()
{
    var rootPath = Environment.CurrentDirectory;//Path.Combine(Environment.CurrentDirectory, "Data");
    var providerManager = new NoesisProviderManager(
        new FolderXamlProvider(rootPath),
        new FolderFontProvider(rootPath),
        new FolderTextureProvider(rootPath, this.GraphicsDevice));

    var config = new NoesisConfig(
        this.Game.Window,
        SadConsole.Global.GraphicsDeviceManager,
        providerManager,
        rootXamlFilePath: "Views/Root.xaml",
        // uncomment this line to use theme file
        themeXamlFilePath: "Themes/NocturnalStyle.xaml",
        currentTotalGameTime: this.lastUpdateTotalGameTime);

    config.SetupInputFromWindows();

    noesisGUIWrapper = new NoesisWrapper(config);

    // My main ViewModel
    noesisGUIWrapper.ControlTreeRoot.DataContext = new Editor.ViewModels.MainViewModel();
}
```

Then my startup code (after my engine is loaded) adds the main view to the empty root grid. Currently this is just some pull down menus:

```csharp
// Load main GUI
var window = new Xaml.MainWindow();
((Noesis.Grid)EditorGameComponent.noesisGUIWrapper.ControlTreeRoot).Children.Add(window);
```

Next the xaml of `MainWindow` has this command bound (it works) to the view model:

```xaml
<MenuItem Header="New Document..." Command="{Binding ShowNewDocument}"></MenuItem>
```

When MonoGame closes down, I call 

```csharp
public static void DestroyGUI()
{
    if (noesisGUIWrapper != null)
    {
        noesisGUIWrapper.Dispose();
        noesisGUIWrapper = null;
    }
}
```

Everything is working fine but if I run the game, then just close it down by closing the window, I get this error randomly.

![noesis-error](https://user-images.githubusercontent.com/2672110/37500345-3f5fae56-2886-11e8-8e94-53f199c8b867.png)

**Comment by aienabled** [comment]
@Thraka yes, it's a known problem with NoesisGUI C# SDK.
Please ensure that you don't interact with any classes/API of NoesisGUI after calling `noesisGUIWrapper.Dispose();` as this will lead to this exception.
The exception stacktrace might help to locate the place where you're interacting with NoesisGUI.

If this happens from a Finalize method (called for any C# control of `NoesisGUI`), I would recommend reporting the bug here http://bugs.noesisengine.com/ and upload the game build to allow them to debug the issue. NoesisGUI C# SDK should clean up all such objects itself during `noesisGUIWrapper.Dispose();` (as it calls `NoesisGUI.Shutdown()`) and so no Finalize calls should be made.
