### ISSUE TITLE
DeviceStateHelperD3D11 has mistake

### ISSUE THREAD

**Issue by ClEngine** [aienabled/NoesisGUI.MonoGameWrapper#5]
Unable to find type or namespace Color4
Unable to find type or namespace Rectangle
Unable to find type or namespace ViewportF

**Comment by aienabled** [comment]
Hello!
Are you using MonoGame `develop` branch?
In that case you need a different version of `DeviceStateHelperD3D11` written for latest `SharpDX` (as I've informed there https://github.com/aienabled/NoesisGUI.MonoGameWrapper/issues/4).
I've uploaded `DeviceStateHelperD3D11` compatible with latest `develop` branch here https://gist.github.com/aienabled/c62d4409eb3f7f84912e09d5956bb012

Regards!

**Comment by ClEngine** [comment]
Thank you for your help, and I succeeded in running it
