### ISSUE TITLE
Full screen mode very buggy and inconsistent

### ISSUE THREAD

**Issue by andrew-sidereal** [aienabled/NoesisGUI.MonoGameWrapper#7]
When testing this in full-screen mode, Noesis inputs don't receive mouse clicks consistently. If one has focus, then I can tab around, or if an input has focus, then I may type in it, but the mouse picking is very inconsistent and usually doesn't do what is expected. To reproduce this, just use the sample project provided and add this line of code at the end of GameWithNoesis.cs constructor:
`
this.graphics.IsFullScreen = true;
`

Please let me know what the resolution is. I may be missing something, but since I'm working with the provided sample project, I'm thinking this may be a bug in the wrapper.

**Comment by aienabled** [comment]
@alundgren04, thanks for reporting!
There is a bug in MonoGame 3.6 - the game doesn't always automatically adjust its backbuffer size to match the game window client bounds (when its resized via dragging or toggling the fullscreen mode). You might have noticed that UI becomes blurry or pixelated when you change the window size. In a such case, the mouse input was also processed against the wrong window size.

I've pushed a commit which resolves the issue by refreshing the backbuffer size to match the game window bounds.

There are also two new constants added - `SettingIsFullscreen` and `SettingIsFullscreenEnforceHardwareMode` please follow [my comments in code here](https://github.com/aienabled/NoesisGUI.MonoGameWrapper/blob/7b331c415de95d6e7f79d63de6879857f188062a/TestMonoGameNoesisGUI/GameWithNoesis.cs#L25).

BTW, we're using the software fullscreen mode in our game CryoFall. I've not noticed the issue you reported as the game is built with MonoGame 3.7 (built directly from the source as it's still not released) and there is no issue with the backbuffer size refreshing.

Regards!

**Comment by Thraka** [comment]
@alundgren04 @aienabled FYI MonoGame version 3.7.0.1681-develop was put on NuGet a month ago

**Comment by andrew-sidereal** [comment]
Kind of incredible there's a bug this large in MonoGame. It gives me concern about what other, more subtle, bugs may exist. 

That said, this fix worked well for me. Thank you!
