### ISSUE TITLE
Update to support NoesisGUI 2.2

### ISSUE THREAD

**Issue by aienabled** [aienabled/NoesisGUI.MonoGameWrapper#8]

**Comment by Thraka** [comment]
Is this going to make things a lot easier now that they have the managed library?

**Comment by aienabled** [comment]
@Thraka there is not much difference in this aspect. The managed SDK previously was distributed as a separate download. Now it's available as a NuGet and source code repository https://github.com/Noesis/Managed I'm considering to provide support for both distributions.

I prefer to use a fork of NoesisGUI Managed SDK (and I've asked them many times to make it available on Github!) - the primary reason is that I need to have 100% WPF API compatibility and original NoesisGUI Managed SDK is using float instead of double for its public API which makes direct usage of C# code from WPF applications not always possible. And several other compatibility problems... See https://github.com/aienabled/Managed

**Comment by jesusdesantos** [comment]
We have been discussing this long time and I think we are going to incorporate all modifications to be 100% compatible with WPF. Float and namespaces included...

**Comment by aienabled** [comment]
Upgraded to support NoesisGUI 3.0.12. Finally!
